# Generated by Django 4.2.7 on 2024-01-22 19:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_urlmodel_remove_blog_blog_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlmodel',
            name='name_url',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='Link Name'),
            preserve_default=False,
        ),
    ]
